### ISSUE TITLE
Choix pour l'équipe : Krabby vs Hypocéan

### ISSUE THREAD

**Issue by Naereen** [Pokemon-via-GitHub-contre-Covid-2020-fr/Version-Jaune#18]
## Rappel du protocole de jeu
Comme [expliqué ici](https://github.com/Pokemon-via-GitHub-contre-Covid-2020-fr/Pokemon-via-GitHub-contre-Covid-2020-fr.github.io#comment-seront-prises-les-d%C3%A9cisions--cf-consensus), les décisions relativement importantes, comme le choix de l'équipe, peuvent être prises par le ou la joueur-se sans consulter les autres participant-e-s, mais il ou elle peut aussi décider [d'ouvrir un ticket](https://github.com/Pokemon-via-GitHub-contre-Covid-2020-fr/Version-Jaune/issues/new) et de soumettre la décision au vote des participant-e-s à la partie en cours.

## Quelle décision doit être prise aujourd'hui ?
Ici, nous devons décider quel Pokémon eau faut-il garder dans l'équipe : Krabby vs Hypocéan.

@Remi100fa1000 proposait Krabby, @Naereen préférait Carapuce ou à défaut Hypocéan, @eleurent disait *"Whatever ils sont tous forts ! L’important c’est l’amour"*.

@xuedong @estey @miles-tenroc votre avis ?
- :+1: pour garder Krabby,
- :-1: pour prendre Hypocéan,
- Commentaire pour d'autre réponse.

**Comment by Remi100fa1000** [comment]
Sinon on capture un Ptitard et on le met dans l'équipe :blush:
