### ISSUE TITLE
[Cable Link] Faire évoluer Kadabra et Gravalanch

### ISSUE THREAD

**Issue by eleurent** [Pokemon-via-GitHub-contre-Covid-2020-fr/Version-Jaune#21]
Le cable Link a l'air supporté par [visualboyadvance-m](https://github.com/visualboyadvance-m/visualboyadvance-m), dans Options / Link.

On peut charger deux fois notre sauvegarde, et échanger Kadabra et Gravalanch entre les deux sessions pour les faire évoluer.

**Comment by eleurent** [comment]
On peut le faire en local mais on pourrait aussi essayer via internet entre deux joueurs

**Comment by Naereen** [comment]
Je m'en occupe aujourd'hui, je refuse de laisser la possibilité de battre la Ligue avec juste un Kadabra ;-)

**Comment by Naereen** [comment]
Sous Windows comme sous Ubuntu, j'arrive à lancer visualboyadvance-m, Pokémon Jaune et à *charger* la sauvegarde. Mais je n'arrive pas à sauvegarder par dessus, il me sort toujours une erreur de la taille du fichier de sauvegarde batterie :

![Capture d’écran_2020-05-06_15-52-20](https://user-images.githubusercontent.com/11994719/81185356-c37db400-8fb1-11ea-8e02-4c56fd0595f4.png)
![Pokemon_Yellow_FRENCH_GBC-HS-105](https://user-images.githubusercontent.com/11994719/81185359-c4164a80-8fb1-11ea-8af9-f1aadba99a45.png)

**Comment by Naereen** [comment]
@eleurent tu veux essayer ?

**Comment by eleurent** [comment]
J'ai essayé:
* avec VBA-m, je n'avais pas de message d'erreur et j'arrivais bien à charger les deux sauvegardes, mais dans le centre pokemon le cable link n'était pas détecté...
* avec [TGB-Dual](https://digiex.net/threads/tgb-dual-vol-8-3-1-english-download-gameboy-emulator-with-link-cable-support.14666/), c'était un peu laborieux (mauvais chargement de la sauvegarde du player 2) mais ça a fini par fonctionner !


![Pokemon_Yellow_FRENCH_GBC-HS_000](https://user-images.githubusercontent.com/1706935/81321415-e03de880-9092-11ea-834a-47ba21b07c95.png) ![Pokemon_Yellow_FRENCH_GBC-HS_001](https://user-images.githubusercontent.com/1706935/81321417-e0d67f00-9092-11ea-8a28-cda41e416b25.png) ![Pokemon_Yellow_FRENCH_GBC-HS_002](https://user-images.githubusercontent.com/1706935/81321421-e0d67f00-9092-11ea-9acf-77f6a528e189.png)
![Pokemon_Yellow_FRENCH_GBC-HS_003](https://user-images.githubusercontent.com/1706935/81321422-e16f1580-9092-11ea-810a-404c27a776c9.png) ![Pokemon_Yellow_FRENCH_GBC-HS_004](https://user-images.githubusercontent.com/1706935/81321424-e16f1580-9092-11ea-94b2-976fa39984c3.png) ![Pokemon_Yellow_FRENCH_GBC-HS_007](https://user-images.githubusercontent.com/1706935/81321425-e207ac00-9092-11ea-891d-ad86cdcc3e48.png)
![Pokemon_Yellow_FRENCH_GBC-HS_008](https://user-images.githubusercontent.com/1706935/81321426-e207ac00-9092-11ea-8b30-fb647b93a234.png) ![Pokemon_Yellow_FRENCH_GBC-HS_009](https://user-images.githubusercontent.com/1706935/81321429-e2a04280-9092-11ea-975d-fda663221ad6.png) ![Pokemon_Yellow_FRENCH_GBC-HS_010](https://user-images.githubusercontent.com/1706935/81321430-e2a04280-9092-11ea-91f7-7c227dd69946.png)
![Pokemon_Yellow_FRENCH_GBC-HS_011](https://user-images.githubusercontent.com/1706935/81321433-e338d900-9092-11ea-96bf-6f03e026b1a8.png) ![Pokemon_Yellow_FRENCH_GBC-HS_012](https://user-images.githubusercontent.com/1706935/81321436-e338d900-9092-11ea-92aa-6c5b42a8f7e3.png) ![Pokemon_Yellow_FRENCH_GBC-HS_013](https://user-images.githubusercontent.com/1706935/81321437-e3d16f80-9092-11ea-9eb8-8e3ead233064.png)
![Pokemon_Yellow_FRENCH_GBC-HS_014](https://user-images.githubusercontent.com/1706935/81321438-e3d16f80-9092-11ea-885d-f92c9f6b6bf8.png) ![Pokemon_Yellow_FRENCH_GBC-HS_016](https://user-images.githubusercontent.com/1706935/81321442-e46a0600-9092-11ea-8ad8-3e8982bc95a0.png)

**Comment by Naereen** [comment]
Bien joué !
